FROM bitnami/kafka:3.1
#CMD ["./opt/bitnami/kafka/bin/kafka-topics.sh", "--bootstrap-server", "kafka1:9092", "--create", "--topic", "all-messages", "--if-not-exists", "--partitions", "1", "--replication-factor", "3"]
#CMD ["./bin/kafka-topics.sh", "--create", "--topic", "all-messages", "--if-not-exists", "--partitions", "1", "--replication-factor", "3"]
# /opt/bitnami/kafka/bin/kafka-topics.sh to run