version: "3.9"

networks:
  my-simple-network:
    driver:
      bridge

services:
#  # https://hub.docker.com/_/zookeeper
#  # https://hub.docker.com/r/bitnami/zookeeper
#  zookeeper:
#    container_name: zookeeper
#    image: zookeeper:3.8.0
#    #hostname: zoo1
#    ports:
#      - "2181:2181"
#    networks:
#      - my-simple-network
#    restart: always
#
#  # https://hub.docker.com/r/bitnami/kafka
#  kafka0:
#    container_name: kafka
#    build: ./kafka-broker
#    #    #image: bitnami/kafka:3.1
#    ##    ports:
#    ##      - '9092:9092'
#    ##      - '9093:9093'
#    ##    environment:
#    ##      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
#    ##      - ALLOW_PLAINTEXT_LISTENER=yes
#    ##      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
#    ##      - KAFKA_CFG_LISTENERS=CLIENT://127.0.0.1:9092,EXTERNAL://:9093
#    ##      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
#    ##      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
#    depends_on:
#      - zookeeper
#    restart: always
#    networks:
#      - my-simple-network
#
#  #    volumes:
#  #      - ./kafka-broker:/bitnami/kafka


  db:
    container_name: ClientDB
    build: ./db
    # image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: passw
      POSTGRES_DB: clients_data
    networks:
      - my-simple-network
    ports:
      - '5438:5432'