#!/bin/zsh

chmod +x startProject
chmod +x stopProject
chmod +x runClient
chmod +x ./ClientCliApp/generateJAR
chmod +x ./KafkaStreamsChatAnalyser/generateJAR
chmod +x ./SparkStreamingAnalyser/generateJAR