#!/bin/zsh

#rm -rf ./back-end/target/universal
#./back-end/generateBin

rm -rf ./KafkaStreamsChatAnalyser/target/scala-2.13
./KafkaStreamsChatAnalyser/generateJAR

docker-compose -f docker-compose.prod.yml up -d