#!/bin/zsh
# before starting project we need generate JAR file of clientCliApp
#./KafkaStreamsChatAnalyser/generateJAR
#./SparkStreamingAnalyser/generateJAR
docker-compose up -d # --build
#./ClientCliApp/generateJAR