#!/bin/zsh

docker stop KessengerDB
docker rm -v KessengerDB
docker rmi kessenger_db      ##   delete unused image

# This may be disabled.
# docker stop pgadmin
# docker rm -v pgadmin

docker stop kafka_streams_chat_analyser
docker rm -v kafka_streams_chat_analyser

docker stop kafka1
docker rm -v kafka1
#docker rmi kessenger_kafka1

docker stop kafka2
docker rm -v kafka2

docker stop kafka3
docker rm -v kafka3

docker stop zookeeper
docker rm -v zookeeper
#docker rmi zookeeper