#!/bin/bash


KESSENGER_MODE="prod"


for ar in $@ ; do
  if [[ $ar = "--env=dev" ]] ; then
    KESSENGER_MODE="dev"
  fi
done


if [[ $KESSENGER_MODE = "dev" ]] ; then
  ./scripts/stopDevBash
else
  ./scripts/stopProdBash
fi
