#!/bin/zsh


kessenger_mode="prod"


for ar in $@ ; do
  if [[ $ar = "--env=dev" ]] ; then
    kessenger_mode="dev"
  fi
done


if [[ $kessenger_mode = "dev" ]] ; then
  ./scripts/stopDev
else
  echo "Closing prod"
  ./scripts/stopProd
fi
