package conf

trait KafkaConf {

  def BOOTSTRAP_SERVERS: String

  def CHAT_TOPIC_REPLICATION_FACTOR: Short
  def CHAT_TOPIC_PARTITIONS_NUMBER: Int
  def USER_SERIALIZER: String
  def USER_DESERIALIZER: String
  def MESSAGE_SERIALIZER: String
  def MESSAGE_DESERIALIZER: String

  def JOINING_TOPIC_REPLICATION_FACTOR: Short
  def JOINING_TOPIC_PARTITIONS_NUMBER: Int
  def INVITATION_SERIALIZER: String
  def INVITATION_DESERIALIZER: String


  def WRITING_TOPIC_REPLICATION_FACTOR: Short
  def WRITING_TOPIC_PARTITIONS_NUMBER: Int
  def WRITING_SERIALIZER: String
  def WRITING_DESERIALIZER: String


}


