#!/bin/zsh
docker build $(pwd)/../db --tag test-db
docker run -d -p 5438:5432 --restart always -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=passw -e POSTGRES_DB=kessenger_schema --name test-db  test-db
