#!/bin/zsh
docker run -d \
 -p 9092:9092 \
 -p 9093:9093 \
 --restart always \
 --network integration-tests-network \
 -e ALLOW_PLAINTEXT_LISTENER=yes \
 -e KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-test:2181 \
 -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT \
 -e KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093 \
 -e KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-test:9092,EXTERNAL://localhost:9093 \
 -e KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT \
 --name kafka-test  \
 bitnami/kafka:3.1