#!/bin/zsh
cd KafkaStreamsChatAnalyser
sbt assembly
jar -uf ./target/scala-2.13/KafkaStreamsChatAnalyser-0.1.0.jar application.conf
jar -uf ./target/scala-2.13/KafkaStreamsChatAnalyser-0.1.0.jar logback.xml
cd ..